ssddOnTop/lms

- .github/pull_request_template.md
- .github/workflows/pr-title-convention.yml
> chore: introduce pr template

- Cargo.lock
- examples/config.json
- lms-core/Cargo.toml
- lms-core/src/config/config.rs
- lms-core/src/config/mod.rs
- lms-core/src/config/reader.rs
- lms-core/src/http/mod.rs
- lms-core/src/http/response.rs
- lms-core/src/lib.rs
- lms-core/src/runtime.rs
**Summary:**  
Introduce config module
Fixes #6 
**Checklist:**
> feat: introduce config module

- .github/workflows/ci.yml
**Summary:**  
add code coverage on all major platforms
Fixes #3
> chore: add LMS CI

- Cargo.lock
- Cargo.toml
- examples/config.json
- generated/.lmsrc.schema.json
- lms-autogen/Cargo.toml
- lms-autogen/src/main.rs
- lms-core/src/config/reader.rs
**Summary:**  
autogenerate config schema for autocompletion and suggestions
Fixes #10 
**Checklist:**
> feat: autogenerate lms config autocompletion schema

- .github/workflows/linter.yml
**Summary:**  
Add CI to check formatting and make sure that any change in config is reflected in config schema
Fixes #16
**Checklist:**
> chore: introduce linter.yml

- .gitignore
- Cargo.lock
- examples/config.json
- generated/.lmsrc.schema.json
- lint.sh
- lms-core/Cargo.toml
- lms-core/src/blueprint/blueprint.rs
- lms-core/src/blueprint/mod.rs
- lms-core/src/config/config.rs
- lms-core/src/config/hash_algo.rs
- lms-core/src/config/mod.rs
- lms-core/src/config/reader.rs
- lms-core/src/lib.rs
**Summary:**  
Fixes #11
**Checklist:**
> chore: introduce blueprint.rs

- .github/workflows/ci.yml
**Summary:**  
Fixes #21
**Checklist:**
> fix(ci.yml): upload coverage report to codecov

- README.md
> fix(readme): incorrect steps

- .nightly/rust-toolchain.toml
- lint.sh
**Summary:**  
Fixes #36
**Checklist:**
> chore(lint): drop prettier and insert nightly dir

- Cargo.lock
- lms-auth/src/auth.rs
- lms-core/Cargo.toml
- lms-core/src/authdb/auth_db.rs
- tests/snapshots/server_spec__server_spec__req-2.snap
- tests/snapshots/server_spec__server_spec__req-3.snap
- tests/snapshots/server_spec__server_spec__req-4.snap
- tests/snapshots/server_spec__server_spec__req-5.snap
- tests/snapshots/server_spec__server_spec__req-6.snap
- tests/snapshots/server_spec__server_spec__req-7.snap
> chore: add response code

- lms-core/src/config/config_module.rs
- lms-core/src/config/reader.rs
- tests/invalid_configs/short_key.json
- tests/server/config.json
**Summary:**  
Fixes #35
**Checklist:**
> chore(reader): make db path relative to config

- examples/config.json
- generated/.lmsrc.schema.json
- lms-core/src/config/config.rs
- tests/invalid_configs/missing_db_path.json
- tests/invalid_configs/short_totp_key.json
- tests/server/config.json
**Summary:**  
Fixes #40
**Checklist:**
> chore(config): convert `snake` to `camelCase`

- lms-auth/src/auth.rs
- lms-core/src/authdb/auth_db.rs
- lms-core/src/config/reader.rs
- tests/server_spec.rs
**Summary:**  
Fixes #45
**Checklist:**
> chore: drop request signature

- Cargo.lock
- Cargo.toml
- lms-core/Cargo.toml
- lms-core/src/authdb/auth_actors.rs
- lms-core/src/http/response.rs
- lms-core/src/lib.rs
- lms-core/src/runtime.rs
- lms-core/src/uid_gen.rs
- lms-file-db/Cargo.toml
- lms-file-db/src/file_config.rs
- lms-file-db/src/lib.rs
- lms-file-db/src/request_handler.rs
- lms-file-db/src/snapshots/lms_file_db__file_config__tests__serialize_file_holder.snap
- lms-file-db/src/snapshots/lms_file_db__file_config__tests__serialize_remote_file_config.snap
- src/cli/rt/file.rs
- src/cli/rt/instance.rs
- src/cli/rt/mod.rs
- tests/server_spec.rs
> feat: file db

- examples/config.json
- generated/.lmsrc.schema.json
- lms-auth/src/auth.rs
- lms-core/src/authdb/auth_actors.rs
- lms-core/src/authdb/auth_db.rs
- lms-core/src/blueprint/blueprint.rs
- lms-core/src/config/batch_info.rs
- lms-core/src/config/config.rs
- lms-core/src/config/course_info.rs
- lms-core/src/config/mod.rs
- src/cli/commands.rs
- src/cli/runner.rs
- tests/invalid_configs/missing_db_path.json
- tests/invalid_configs/short_key.json
- tests/invalid_configs/short_totp_key.json
- tests/server/config.json
- tests/server_spec.rs
**Summary:**  
Fixes #43
**Checklist:**
> chore(config): add batch and course info

- lms-core/src/actions_db/actions_db.rs
> chore: enhance actions_db.rs tests

- .github/workflows/ci.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- lms-core/Cargo.toml
- lms-core/src/actions_db/actions_db.rs
- lms-core/src/http/mod.rs
- lms-core/src/http/request.rs
- lms-core/src/http/request_handler.rs
- lms-core/src/lib.rs
- lms-core/src/runtime.rs
- lms-wasm/.cargo/config
- lms-wasm/Cargo.toml
- lms-wasm/package.json
- lms-wasm/src/env.rs
- lms-wasm/src/file.rs
- lms-wasm/src/handle.rs
- lms-wasm/src/http.rs
- lms-wasm/src/instance.rs
- lms-wasm/src/lib.rs
- lms-wasm/src/runtime.rs
- lms-wasm/tests/cf_tests.spec.ts
- lms-wasm/tests/mf.ts
- lms-wasm/wrangler.toml
- src/cli/rt/env.rs
- src/cli/rt/mod.rs
- src/cli/server/http1.rs
- tests/server_spec.rs
**Summary:**  
Fixes #58
**Checklist:**
> feat: bring wasm support

- lms-auth/src/auth.rs
- lms-core/src/actions_db/actions.rs
- lms-core/src/actions_db/actions_db.rs
- lms-core/src/authdb/auth_db.rs
- lms-wasm/tests/cf_tests.spec.ts
- tests/server_spec.rs
- tests/snapshots/server_spec__server_spec__req-2.snap
**Summary:**  
Fixes #61
**Checklist:**
> chore: drop AES encryption and decryption of req

- lms-auth/src/auth.rs
- lms-core/src/actions_db/actions.rs
- lms-core/src/actions_db/actions_db.rs
- lms-core/src/authdb/auth_db.rs
- lms-wasm/tests/cf_tests.spec.ts
- tests/server_spec.rs
- tests/snapshots/server_spec__server_spec__req-2.snap
> chore: drop req encryption

- examples/config.json
- lms-core/src/actions_db/actions_db.rs
- lms-core/src/authdb/auth_db.rs
> fix(config.json): example batch and courses

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- html/index.js
- html/login.html
- lms-core/Cargo.toml
- lms-core/src/authdb/auth_actors.rs
- lms-core/src/authdb/auth_db.rs
- lms-core/src/blueprint/blueprint.rs
- lms-core/src/http/mod.rs
- lms-core/src/http/request_handler.rs
- lms-macros/Cargo.toml
- lms-macros/src/lib.rs
- lms-wasm/src/handle.rs
- src/cli/commands.rs
- src/cli/rt/instance.rs
- src/cli/runner.rs
- src/cli/server/http1.rs
> chore: add login page
